call compile preprocessFileLineNumbers "HC\Headless_Client\HCsignals.sqf";
HCdo_spawnRCV = compile preprocessFileLineNumbers "HC\Headless_Client\HCdo_spawnRCV.sqf";
call compile preprocessFileLineNumbers "HC\Headless_Client\handle_HCdo_spawnRCV.sqf";
nearest_player = compile preprocessFileLineNumbers "HC\compiles\nearest_player.sqf";
zombie_loiterHC = compile preprocessFileLineNumbers "HC\compiles\zombie_loiterHC.sqf";
zombie_generateHC = compile preprocessFileLineNumbers "HC\compiles\zombie_generateHC.sqf";
building_spawnZombiesHC = compile preprocessFileLineNumbers "HC\compiles\building_spawnZombiesHC.sqf";
wild_spawnZombiesHC = compile preprocessFileLineNumbers "HC\compiles\wild_spawnZombiesHC.sqf";
player_spawnCheck = compile preprocessFileLineNumbers "HC\compiles\player_spawnCheck.sqf";
player_zombieAttack = compile preprocessFileLineNumbers "HC\compiles\player_zombieAttack.sqf";
